In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.tree import DecisionTreeClassifier as DTC
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv('../Data/processed/data_modeling.csv')
data.head()

,id_partido,Equipo_local,Goles_avg5_local,goles_rival_avg5_local,tiros_avg5_local,tiros_al_arco_avg5_local,corners_avg5_local,faltas_avg5_local,amarillas_avg5_local,rojas_avg5_local,...,faltas_avg5_visitante,amarillas_avg5_visitante,rojas_avg5_visitante,goles_ht_avg5_visitante,goles_ht_rival_avg5_visitante,resultado_avg5_visitante,B365H,B365D,B365A,FTR
0,1951,Barcelona,1.8,1.0,18.2,7.2,7.0,19.2,2.0,0.0,...,22.0,3.4,0.0,0.6,0.4,1.4,1.33,4.50,9.50,D
1,1952,Getafe,1.8,1.0,13.2,5.6,4.4,23.0,3.4,0.4,...,21.0,2.4,0.2,0.4,0.8,1.8,2.60,3.20,2.62,H
2,1953,Cadiz,0.6,1.0,7.6,3.4,6.6,16.0,2.4,0.0,...,18.0,1.4,0.0,1.2,0.4,2.4,2.50,3.20,2.75,D
3,1954,La Coruna,1.2,0.8,13.4,4.8,4.6,16.8,3.0,0.2,...,22.8,4.2,0.2,0.4,0.0,1.8,1.66,3.40,5.50,A
4,1955,Malaga,1.4,1.2,11.4,4.6,4.6,20.4,2.0,0.2,...,21.2,2.4,0.2,0.6,0.2,0.8,2.40,3.25,2.80,A

In [3]:
data.describe()

,id_partido,Goles_avg5_local,goles_rival_avg5_local,tiros_avg5_local,tiros_al_arco_avg5_local,corners_avg5_local,faltas_avg5_local,amarillas_avg5_local,rojas_avg5_local,goles_ht_avg5_local,...,corners_avg5_visitante,faltas_avg5_visitante,amarillas_avg5_visitante,rojas_avg5_visitante,goles_ht_avg5_visitante,goles_ht_rival_avg5_visitante,resultado_avg5_visitante,B365H,B365D,B365A
count,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000,...,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000,7717.000000
mean,5880.668524,1.307658,1.348996,12.088247,4.264351,4.932539,14.560270,2.533705,0.148996,0.575664,...,5.062408,14.557393,2.509628,0.146534,0.599093,0.576571,1.410704,2.657750,3.964757,4.808795
std,2255.803781,0.659877,0.583584,2.757686,1.379623,1.394057,3.050716,0.736996,0.177713,0.388513,...,1.420659,3.061210,0.733404,0.177236,0.399863,0.355816,0.670920,2.005311,1.493206,4.318629
min,1951.000000,0.000000,0.000000,4.200000,0.600000,0.800000,5.800000,0.600000,0.000000,0.000000,...,1.000000,5.800000,0.400000,0.000000,0.000000,0.000000,0.000000,1.020000,2.500000,1.080000
25%,3933.000000,0.800000,1.000000,10.200000,3.400000,4.000000,12.400000,2.000000,0.000000,0.200000,...,4.000000,12.400000,2.000000,0.000000,0.400000,0.400000,0.800000,1.670000,3.250000,2.600000
50%,5892.000000,1.200000,1.400000,11.800000,4.000000,4.800000,14.400000,2.600000,0.200000,0.600000,...,5.000000,14.200000,2.400000,0.200000,0.600000,0.600000,1.400000,2.100000,3.400000,3.500000
75%,7836.000000,1.600000,1.800000,13.600000,5.000000,5.800000,16.400000,3.000000,0.200000,0.800000,...,6.000000,16.400000,3.000000,0.200000,0.800000,0.800000,1.800000,2.800000,4.000000,5.250000
max,9770.000000,5.400000,4.000000,24.200000,11.800000,12.000000,28.200000,5.200000,1.400000,2.800000,...,11.400000,28.800000,5.400000,1.200000,3.200000,2.400000,3.000000,26.000000,17.000000,41.000000

In [4]:
data.isnull().sum()

id_partido                       0
Equipo_local                     0
Goles_avg5_local                 0
goles_rival_avg5_local           0
tiros_avg5_local                 0
tiros_al_arco_avg5_local         0
corners_avg5_local               0
faltas_avg5_local                0
amarillas_avg5_local             0
rojas_avg5_local                 0
goles_ht_avg5_local              0
goles_ht_rival_avg5_local        0
resultado_avg5_local             0
temporada                        0
Date                             0
Equipo_visitante                 0
Goles_avg5_visitante             0
goles_rival_avg5_visitante       0
tiros_avg5_visitante             0
tiros_al_arco_avg5_visitante     0
corners_avg5_visitante           0
faltas_avg5_visitante            0
amarillas_avg5_visitante         0
rojas_avg5_visitante             0
goles_ht_avg5_visitante          0
goles_ht_rival_avg5_visitante    0
resultado_avg5_visitante         0
B365H                            0
B365D                            0
B365A                            0
FTR                              0
dtype: int64

Teniendo en cuenta la informacion hallada de que las apuestas tienen en base un acierto del 53.5%, esta informacion la tomaremos como base de nuestro modelo, donde se buscara mejor tal porcentaje

In [6]:
x_features = \
['Goles_avg5_local',
 'goles_rival_avg5_local',
 'tiros_avg5_local',
 'tiros_al_arco_avg5_local',
 'corners_avg5_local',
 'faltas_avg5_local',
 'amarillas_avg5_local',
 'rojas_avg5_local',
 'goles_ht_avg5_local',
 'goles_ht_rival_avg5_local',
 'resultado_avg5_local',
 'Goles_avg5_visitante',
 'goles_rival_avg5_visitante',
 'tiros_avg5_visitante',
 'tiros_al_arco_avg5_visitante',
 'corners_avg5_visitante',
 'faltas_avg5_visitante',
 'amarillas_avg5_visitante',
 'rojas_avg5_visitante',
 'goles_ht_avg5_visitante',
 'goles_ht_rival_avg5_visitante',
 'resultado_avg5_visitante',
 'B365H',
 'B365D',
 'B365A']

In [7]:
temp = [2425, 2526]
train_x = data[~data['temporada'].isin(temp)][x_features]
train_y = data[~data['temporada'].isin(temp)]['FTR']
test_x = data[data['temporada']==2425][x_features]
test_y = data[data['temporada']==2425]['FTR']
validation_x = data[data['temporada']==2526][x_features]
validation_y = data[data['temporada']==2526]['FTR']

In [8]:
print(train_x.shape, train_y.shape)
print(test_x.shape, test_y.shape)
print(validation_x.shape, validation_y.shape)

(7072, 25) (7072,)
(380, 25) (380,)
(265, 25) (265,)

In [9]:
baseline_test = test_x[['B365H','B365A','B365D']].idxmin(axis=1,skipna=False).str[-1]

In [10]:
(baseline_test == test_y).mean()

np.float64(0.5447368421052632)

In [11]:
clf = DTC(random_state=42)
clf.fit(train_x, train_y)

DecisionTreeClassifier(random_state=42)

In [12]:
y_pred = clf.predict(test_x)

accuracy = accuracy_score(test_y, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.4052631578947368

In [13]:
accuracy = accuracy_score(train_y, clf.predict(train_x))
print(f'Accuracy: {accuracy}')

Accuracy: 1.0

El modelo de arbol de decision tiene una mal % de acierto en la prueba, pero en el entrenamiento tiene un arcierto del 100%, esto indica un sobreajuste del modelo.

In [14]:
from sklearn.model_selection import TimeSeriesSplit, GridSearchCV

In [15]:
param_grid = {
    'max_depth': [1,3,5,7,9],
    'min_samples_leaf': [1,3,5,7,9],
    'min_samples_split': [2,4,6,8,10],
    'criterion': ["entropy", "gini"]
}

In [16]:
tscv = TimeSeriesSplit(n_splits=5)
gsearch = GridSearchCV(estimator=clf, cv=tscv,
                        param_grid=param_grid)

In [17]:
gsearch.fit(train_x, train_y)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': [1, 3, 5, 7, 9],
                         'min_samples_leaf': [1, 3, 5, 7, 9],
                         'min_samples_split': [2, 4, 6, 8, 10]})

In [18]:
y_pred = gsearch.best_estimator_.predict(test_x)

accuracy = accuracy_score(test_y, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.5605263157894737

Cuando se ajusta el modelo mejora su rendimiento, llegando a mejorar la que realiza las de las apuestas

In [19]:
from sklearn.metrics import classification_report

print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           A       0.54      0.61      0.57       114
           D       0.00      0.00      0.00        97
           H       0.57      0.85      0.68       169

    accuracy                           0.56       380
   macro avg       0.37      0.49      0.42       380
weighted avg       0.42      0.56      0.48       380

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Aun se tiene problemas para poder predecir los partidos que terminan en empate

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [38]:
param_grid_rf = \
                {'n_estimators': [100,150],
                 'max_features': [5, 7, 9],
                 'max_depth'   : [1, 3, 10],
                 'min_samples_leaf': [1, 3, 5],
                 'min_samples_split': [2, 4, 6],
                 'criterion': ["entropy", "gini"],
                 'n_jobs': [-1]
                }

rf = RandomForestClassifier(random_state=42,n_jobs=-1)

In [39]:
gsearch_rf = GridSearchCV(estimator=rf, cv=tscv,param_grid=param_grid_rf)
gsearch_rf.fit(train_x, train_y)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': [1, 3, 10], 'max_features': [5, 7, 9],
                         'min_samples_leaf': [1, 3, 5],
                         'min_samples_split': [2, 4, 6],
                         'n_estimators': [100, 150], 'n_jobs': [-1]})

In [40]:
gsearch_rf.best_params_

{'criterion': 'entropy',
 'max_depth': 3,
 'max_features': 9,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 150,
 'n_jobs': -1}

In [41]:
y_pred_rf = gsearch_rf.best_estimator_.predict(test_x)

accuracy_rf = accuracy_score(test_y, y_pred_rf)
print(f'Accuracy: {accuracy_rf}')

Accuracy: 0.5526315789473685

In [42]:
print(classification_report(test_y, y_pred_rf))

              precision    recall  f1-score   support

           A       0.55      0.58      0.56       114
           D       0.00      0.00      0.00        97
           H       0.55      0.85      0.67       169

    accuracy                           0.55       380
   macro avg       0.37      0.48      0.41       380
weighted avg       0.41      0.55      0.47       380

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [43]:
from xgboost import XGBClassifier

In [44]:
map_resultado = {'H': 0, 'D': 1, 'A': 2}
y_train_mapped = train_y.map(map_resultado)
y_test_mapped = test_y.map(map_resultado)