## Importacion de Libreria

In [1]:
import json
import requests
import pyodbc
import pandas as pd
from datetime import datetime
from dotenv import load_dotenv
import os

In [30]:
#Obtencion de servidor Sql y API de https://api.football-data.org

load_dotenv()  # ← carga el .env

API_KEY = os.getenv("FOOTBALL_API_KEY")  # ← define la variable
DB_SERVER = os.getenv("DB_SERVER")
DB_NAME = os.getenv("DB_NAME")

In [4]:
# Conectar la info del API al SQL y guardar los datos en la base de datos para su posterior análisis.

conn = pyodbc.connect(
    f"DRIVER={{SQL Server}};"
    f"SERVER={DB_SERVER};"
    f"DATABASE={DB_NAME};"
    "Trusted_Connection=yes;"
)
cursor = conn.cursor()

## Obtener ID de la liga española

In [4]:
### Extracting data from API
URL = 'https://api.football-data.org/v4/competitions'
credenciales = {'X-Auth-Token': API_KEY}

response = requests.get(URL,headers=credenciales)
data = response.json()

In [5]:
print(json.dumps(data['competitions'][0], indent=2))

{
  "id": 2013,
  "area": {
    "id": 2032,
    "name": "Brazil",
    "code": "BRA",
    "flag": "https://crests.football-data.org/764.svg"
  },
  "name": "Campeonato Brasileiro S\u00e9rie A",
  "code": "BSA",
  "type": "LEAGUE",
  "emblem": "https://crests.football-data.org/bsa.png",
  "plan": "TIER_ONE",
  "currentSeason": {
    "id": 2474,
    "startDate": "2026-01-28",
    "endDate": "2026-12-02",
    "currentMatchday": 6,
    "winner": null
  },
  "numberOfAvailableSeasons": 10,
  "lastUpdated": "2024-09-13T16:55:53Z"
}

In [6]:
for competicion in data['competitions']:
    print(f"ID: {competicion['id']}, Name: {competicion['name']}") # El ID de la Liga Española es 2014

ID: 2013, Name: Campeonato Brasileiro Série A
ID: 2016, Name: Championship
ID: 2021, Name: Premier League
ID: 2001, Name: UEFA Champions League
ID: 2018, Name: European Championship
ID: 2015, Name: Ligue 1
ID: 2002, Name: Bundesliga
ID: 2019, Name: Serie A
ID: 2003, Name: Eredivisie
ID: 2017, Name: Primeira Liga
ID: 2152, Name: Copa Libertadores
ID: 2014, Name: Primera Division
ID: 2000, Name: FIFA World Cup

El ID que utilizaremos es el 2014 ya que estamos interesados en la liga española

## Insertar Datos de Competicion
* Informacion de la Liga Española

In [7]:
URL = 'https://api.football-data.org/v4/competitions/2014'
response = requests.get(URL, headers=credenciales)
comp = response.json()
print(json.dumps(comp, indent=2))

{
  "area": {
    "id": 2224,
    "name": "Spain",
    "code": "ESP",
    "flag": "https://crests.football-data.org/760.svg"
  },
  "id": 2014,
  "name": "Primera Division",
  "code": "PD",
  "type": "LEAGUE",
  "emblem": "https://crests.football-data.org/laliga.png",
  "currentSeason": {
    "id": 2429,
    "startDate": "2025-08-17",
    "endDate": "2026-05-24",
    "currentMatchday": 28,
    "winner": null
  },
  "seasons": [
    {
      "id": 2429,
      "startDate": "2025-08-17",
      "endDate": "2026-05-24",
      "currentMatchday": 28,
      "winner": null
    },
    {
      "id": 2292,
      "startDate": "2024-08-18",
      "endDate": "2025-05-25",
      "currentMatchday": 38,
      "winner": null
    },
    {
      "id": 1577,
      "startDate": "2023-08-13",
      "endDate": "2024-05-26",
      "currentMatchday": 38,
      "winner": null
    },
    {
      "id": 1504,
      "startDate": "2022-08-14",
      "endDate": "2023-06-04",
      "currentMatchday": 38,
      "winner": null
    },
    {
      "id": 380,
      "startDate": "2021-08-13",
      "endDate": "2022-05-22",
      "currentMatchday": 38,
      "winner": null
    },
    {
      "id": 635,
      "startDate": "2020-09-12",
      "endDate": "2021-05-23",
      "currentMatchday": 38,
      "winner": {
        "id": 78,
        "name": "Club Atl\u00e9tico de Madrid",
        "shortName": "Atleti",
        "tla": "ATL",
        "crest": "https://crests.football-data.org/78.png",
        "address": "Paseo Virgen del Puerto, 67 Madrid 28005",
        "website": "http://www.clubatleticodemadrid.com",
        "founded": 1903,
        "clubColors": "Red / White / Blue",
        "venue": "Estadio Wanda Metropolitano",
        "lastUpdated": "2024-07-29T17:08:58Z"
      }
    },
    {
      "id": 519,
      "startDate": "2019-08-16",
      "endDate": "2020-07-19",
      "currentMatchday": 38,
      "winner": {
        "id": 86,
        "name": "Real Madrid CF",
        "shortName": "Real Madrid",
        "tla": "RMA",
        "crest": "https://crests.football-data.org/86.png",
        "address": "Avenida Concha Espina, 1 Madrid 28036",
        "website": "http://www.realmadrid.com",
        "founded": 1902,
        "clubColors": "White / Purple",
        "venue": "Estadio Santiago Bernab\u00e9u",
        "lastUpdated": "2022-02-19T08:59:31Z"
      }
    },
    {
      "id": 281,
      "startDate": "2018-08-17",
      "endDate": "2019-05-19",
      "currentMatchday": 38,
      "winner": {
        "id": 81,
        "name": "FC Barcelona",
        "shortName": "Bar\u00e7a",
        "tla": "FCB",
        "crest": "https://crests.football-data.org/81.png",
        "address": "Avenida Ar\u00edstides Maillol s/n Barcelona 08028",
        "website": "http://www.fcbarcelona.com",
        "founded": 1899,
        "clubColors": "Red / Navy Blue / Orange",
        "venue": "Camp Nou",
        "lastUpdated": "2024-07-29T17:09:22Z"
      }
    },
    {
      "id": 16,
      "startDate": "2017-08-18",
      "endDate": "2018-05-20",
      "currentMatchday": 38,
      "winner": {
        "id": 81,
        "name": "FC Barcelona",
        "shortName": "Bar\u00e7a",
        "tla": "FCB",
        "crest": "https://crests.football-data.org/81.png",
        "address": "Avenida Ar\u00edstides Maillol s/n Barcelona 08028",
        "website": "http://www.fcbarcelona.com",
        "founded": 1899,
        "clubColors": "Red / Navy Blue / Orange",
        "venue": "Camp Nou",
        "lastUpdated": "2024-07-29T17:09:22Z"
      }
    },
    {
      "id": 364,
      "startDate": "2016-08-19",
      "endDate": "2017-05-21",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 365,
      "startDate": "2015-08-22",
      "endDate": "2016-05-15",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 366,
      "startDate": "2014-08-24",
      "endDate": "2015-05-23",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 367,
      "startDate": "2013-08-17",
      "endDate": "2014-05-18",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 368,
      "startDate": "2012-08-18",
      "endDate": "2013-06-01",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 369,
      "startDate": "2011-08-27",
      "endDate": "2012-05-13",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 370,
      "startDate": "2010-08-28",
      "endDate": "2011-05-21",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 381,
      "startDate": "2009-08-29",
      "endDate": "2010-05-16",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 382,
      "startDate": "2008-08-30",
      "endDate": "2009-05-31",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 383,
      "startDate": "2007-08-25",
      "endDate": "2008-05-18",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 384,
      "startDate": "2006-08-26",
      "endDate": "2007-06-17",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 385,
      "startDate": "2005-08-27",
      "endDate": "2006-05-20",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 371,
      "startDate": "2004-08-28",
      "endDate": "2005-05-29",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 372,
      "startDate": "2003-08-30",
      "endDate": "2004-05-23",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 386,
      "startDate": "2002-08-31",
      "endDate": "2003-06-22",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1041,
      "startDate": "2001-08-23",
      "endDate": "2002-05-09",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 373,
      "startDate": "2000-09-09",
      "endDate": "2001-06-17",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 374,
      "startDate": "1999-08-21",
      "endDate": "2000-05-20",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 375,
      "startDate": "1998-08-29",
      "endDate": "1999-06-20",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 376,
      "startDate": "1997-08-30",
      "endDate": "1998-05-16",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 377,
      "startDate": "1996-08-31",
      "endDate": "1997-06-15",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 378,
      "startDate": "1995-09-02",
      "endDate": "1996-05-26",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 379,
      "startDate": "1994-09-03",
      "endDate": "1995-06-18",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 387,
      "startDate": "1993-09-05",
      "endDate": "1994-05-15",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1042,
      "startDate": "1992-09-03",
      "endDate": "1993-06-18",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1043,
      "startDate": "1991-08-29",
      "endDate": "1992-06-05",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1065,
      "startDate": "1990-08-30",
      "endDate": "1991-06-07",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1064,
      "startDate": "1989-08-31",
      "endDate": "1990-05-04",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1044,
      "startDate": "1988-09-01",
      "endDate": "1989-06-23",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1045,
      "startDate": "1987-08-27",
      "endDate": "1988-05-20",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1429,
      "startDate": "1986-08-30",
      "endDate": "1987-06-21",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1047,
      "startDate": "1985-08-29",
      "endDate": "1986-04-18",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1048,
      "startDate": "1984-08-30",
      "endDate": "1985-04-19",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1049,
      "startDate": "1983-09-01",
      "endDate": "1984-04-27",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1050,
      "startDate": "1982-09-02",
      "endDate": "1983-04-29",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1046,
      "startDate": "1981-09-17",
      "endDate": "1982-04-23",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1051,
      "startDate": "1980-09-04",
      "endDate": "1981-04-24",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1052,
      "startDate": "1979-09-06",
      "endDate": "1980-05-16",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1053,
      "startDate": "1978-08-31",
      "endDate": "1979-06-01",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1054,
      "startDate": "1977-09-01",
      "endDate": "1978-05-05",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1055,
      "startDate": "1976-09-02",
      "endDate": "1977-06-06",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1056,
      "startDate": "1975-09-04",
      "endDate": "1976-05-14",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1057,
      "startDate": "1974-09-05",
      "endDate": "1975-05-23",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1058,
      "startDate": "1973-08-30",
      "endDate": "1974-05-18",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1059,
      "startDate": "1972-08-31",
      "endDate": "1973-05-18",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1060,
      "startDate": "1971-09-02",
      "endDate": "1972-05-12",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1061,
      "startDate": "1970-09-10",
      "endDate": "1971-04-16",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1062,
      "startDate": "1969-09-11",
      "endDate": "1970-04-17",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1063,
      "startDate": "1968-09-12",
      "endDate": "1969-04-18",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1428,
      "startDate": "1967-09-09",
      "endDate": "1968-04-28",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1066,
      "startDate": "1966-09-08",
      "endDate": "1967-04-21",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1067,
      "startDate": "1965-09-02",
      "endDate": "1966-04-01",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1068,
      "startDate": "1964-09-11",
      "endDate": "1965-04-16",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1069,
      "startDate": "1963-09-13",
      "endDate": "1964-04-24",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1070,
      "startDate": "1962-09-14",
      "endDate": "1963-04-19",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1071,
      "startDate": "1961-08-31",
      "endDate": "1962-03-30",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1072,
      "startDate": "1960-09-09",
      "endDate": "1961-04-28",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1073,
      "startDate": "1959-09-11",
      "endDate": "1960-04-15",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1074,
      "startDate": "1958-09-12",
      "endDate": "1959-04-17",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1075,
      "startDate": "1957-09-13",
      "endDate": "1958-05-02",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1076,
      "startDate": "1956-09-07",
      "endDate": "1957-04-19",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1077,
      "startDate": "1955-09-09",
      "endDate": "1956-04-20",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1078,
      "startDate": "1954-09-10",
      "endDate": "1955-04-08",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1079,
      "startDate": "1953-09-11",
      "endDate": "1954-04-23",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1080,
      "startDate": "1952-09-12",
      "endDate": "1953-05-01",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1081,
      "startDate": "1951-09-07",
      "endDate": "1952-04-11",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1082,
      "startDate": "1950-09-08",
      "endDate": "1951-04-20",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1083,
      "startDate": "1949-09-02",
      "endDate": "1950-04-21",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1084,
      "startDate": "1948-09-10",
      "endDate": "1949-04-15",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1085,
      "startDate": "1947-09-19",
      "endDate": "1948-04-09",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1086,
      "startDate": "1946-09-20",
      "endDate": "1947-04-21",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1087,
      "startDate": "1945-09-21",
      "endDate": "1946-03-29",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1088,
      "startDate": "1944-09-22",
      "endDate": "1945-05-18",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1089,
      "startDate": "1943-09-24",
      "endDate": "1944-04-07",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1090,
      "startDate": "1942-09-25",
      "endDate": "1943-04-02",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1091,
      "startDate": "1941-09-26",
      "endDate": "1942-04-03",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1092,
      "startDate": "1940-09-27",
      "endDate": "1941-03-28",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1093,
      "startDate": "1939-12-01",
      "endDate": "1940-04-26",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1094,
      "startDate": "1935-11-08",
      "endDate": "1936-04-17",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1095,
      "startDate": "1934-11-30",
      "endDate": "1935-04-26",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1096,
      "startDate": "1933-11-03",
      "endDate": "1934-03-02",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1097,
      "startDate": "1932-11-25",
      "endDate": "1933-03-26",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1098,
      "startDate": "1931-11-20",
      "endDate": "1932-04-01",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1099,
      "startDate": "1930-12-05",
      "endDate": "1931-04-03",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1100,
      "startDate": "1929-11-29",
      "endDate": "1930-03-28",
      "currentMatchday": null,
      "winner": null
    },
    {
      "id": 1101,
      "startDate": "1928-02-08",
      "endDate": "1929-06-28",
      "currentMatchday": null,
      "winner": null
    }
  ],
  "lastUpdated": "2024-09-13T16:52:33Z"
}

In [8]:
for key, value in comp.items():
    print(f"{key}: {value}")

area: {'id': 2224, 'name': 'Spain', 'code': 'ESP', 'flag': 'https://crests.football-data.org/760.svg'}
id: 2014
name: Primera Division
code: PD
type: LEAGUE
emblem: https://crests.football-data.org/laliga.png
currentSeason: {'id': 2429, 'startDate': '2025-08-17', 'endDate': '2026-05-24', 'currentMatchday': 28, 'winner': None}
seasons: [{'id': 2429, 'startDate': '2025-08-17', 'endDate': '2026-05-24', 'currentMatchday': 28, 'winner': None}, {'id': 2292, 'startDate': '2024-08-18', 'endDate': '2025-05-25', 'currentMatchday': 38, 'winner': None}, {'id': 1577, 'startDate': '2023-08-13', 'endDate': '2024-05-26', 'currentMatchday': 38, 'winner': None}, {'id': 1504, 'startDate': '2022-08-14', 'endDate': '2023-06-04', 'currentMatchday': 38, 'winner': None}, {'id': 380, 'startDate': '2021-08-13', 'endDate': '2022-05-22', 'currentMatchday': 38, 'winner': None}, {'id': 635, 'startDate': '2020-09-12', 'endDate': '2021-05-23', 'currentMatchday': 38, 'winner': {'id': 78, 'name': 'Club Atlético de Madrid', 'shortName': 'Atleti', 'tla': 'ATL', 'crest': 'https://crests.football-data.org/78.png', 'address': 'Paseo Virgen del Puerto, 67 Madrid 28005', 'website': 'http://www.clubatleticodemadrid.com', 'founded': 1903, 'clubColors': 'Red / White / Blue', 'venue': 'Estadio Wanda Metropolitano', 'lastUpdated': '2024-07-29T17:08:58Z'}}, {'id': 519, 'startDate': '2019-08-16', 'endDate': '2020-07-19', 'currentMatchday': 38, 'winner': {'id': 86, 'name': 'Real Madrid CF', 'shortName': 'Real Madrid', 'tla': 'RMA', 'crest': 'https://crests.football-data.org/86.png', 'address': 'Avenida Concha Espina, 1 Madrid 28036', 'website': 'http://www.realmadrid.com', 'founded': 1902, 'clubColors': 'White / Purple', 'venue': 'Estadio Santiago Bernabéu', 'lastUpdated': '2022-02-19T08:59:31Z'}}, {'id': 281, 'startDate': '2018-08-17', 'endDate': '2019-05-19', 'currentMatchday': 38, 'winner': {'id': 81, 'name': 'FC Barcelona', 'shortName': 'Barça', 'tla': 'FCB', 'crest': 'https://crests.football-data.org/81.png', 'address': 'Avenida Arístides Maillol s/n Barcelona 08028', 'website': 'http://www.fcbarcelona.com', 'founded': 1899, 'clubColors': 'Red / Navy Blue / Orange', 'venue': 'Camp Nou', 'lastUpdated': '2024-07-29T17:09:22Z'}}, {'id': 16, 'startDate': '2017-08-18', 'endDate': '2018-05-20', 'currentMatchday': 38, 'winner': {'id': 81, 'name': 'FC Barcelona', 'shortName': 'Barça', 'tla': 'FCB', 'crest': 'https://crests.football-data.org/81.png', 'address': 'Avenida Arístides Maillol s/n Barcelona 08028', 'website': 'http://www.fcbarcelona.com', 'founded': 1899, 'clubColors': 'Red / Navy Blue / Orange', 'venue': 'Camp Nou', 'lastUpdated': '2024-07-29T17:09:22Z'}}, {'id': 364, 'startDate': '2016-08-19', 'endDate': '2017-05-21', 'currentMatchday': None, 'winner': None}, {'id': 365, 'startDate': '2015-08-22', 'endDate': '2016-05-15', 'currentMatchday': None, 'winner': None}, {'id': 366, 'startDate': '2014-08-24', 'endDate': '2015-05-23', 'currentMatchday': None, 'winner': None}, {'id': 367, 'startDate': '2013-08-17', 'endDate': '2014-05-18', 'currentMatchday': None, 'winner': None}, {'id': 368, 'startDate': '2012-08-18', 'endDate': '2013-06-01', 'currentMatchday': None, 'winner': None}, {'id': 369, 'startDate': '2011-08-27', 'endDate': '2012-05-13', 'currentMatchday': None, 'winner': None}, {'id': 370, 'startDate': '2010-08-28', 'endDate': '2011-05-21', 'currentMatchday': None, 'winner': None}, {'id': 381, 'startDate': '2009-08-29', 'endDate': '2010-05-16', 'currentMatchday': None, 'winner': None}, {'id': 382, 'startDate': '2008-08-30', 'endDate': '2009-05-31', 'currentMatchday': None, 'winner': None}, {'id': 383, 'startDate': '2007-08-25', 'endDate': '2008-05-18', 'currentMatchday': None, 'winner': None}, {'id': 384, 'startDate': '2006-08-26', 'endDate': '2007-06-17', 'currentMatchday': None, 'winner': None}, {'id': 385, 'startDate': '2005-08-27', 'endDate': '2006-05-20', 'currentMatchday': None, 'winner': None}, {'id': 371, 'startDate': '2004-08-28', 'endDate': '2005-05-29', 'currentMatchday': None, 'winner': None}, {'id': 372, 'startDate': '2003-08-30', 'endDate': '2004-05-23', 'currentMatchday': None, 'winner': None}, {'id': 386, 'startDate': '2002-08-31', 'endDate': '2003-06-22', 'currentMatchday': None, 'winner': None}, {'id': 1041, 'startDate': '2001-08-23', 'endDate': '2002-05-09', 'currentMatchday': None, 'winner': None}, {'id': 373, 'startDate': '2000-09-09', 'endDate': '2001-06-17', 'currentMatchday': None, 'winner': None}, {'id': 374, 'startDate': '1999-08-21', 'endDate': '2000-05-20', 'currentMatchday': None, 'winner': None}, {'id': 375, 'startDate': '1998-08-29', 'endDate': '1999-06-20', 'currentMatchday': None, 'winner': None}, {'id': 376, 'startDate': '1997-08-30', 'endDate': '1998-05-16', 'currentMatchday': None, 'winner': None}, {'id': 377, 'startDate': '1996-08-31', 'endDate': '1997-06-15', 'currentMatchday': None, 'winner': None}, {'id': 378, 'startDate': '1995-09-02', 'endDate': '1996-05-26', 'currentMatchday': None, 'winner': None}, {'id': 379, 'startDate': '1994-09-03', 'endDate': '1995-06-18', 'currentMatchday': None, 'winner': None}, {'id': 387, 'startDate': '1993-09-05', 'endDate': '1994-05-15', 'currentMatchday': None, 'winner': None}, {'id': 1042, 'startDate': '1992-09-03', 'endDate': '1993-06-18', 'currentMatchday': None, 'winner': None}, {'id': 1043, 'startDate': '1991-08-29', 'endDate': '1992-06-05', 'currentMatchday': None, 'winner': None}, {'id': 1065, 'startDate': '1990-08-30', 'endDate': '1991-06-07', 'currentMatchday': None, 'winner': None}, {'id': 1064, 'startDate': '1989-08-31', 'endDate': '1990-05-04', 'currentMatchday': None, 'winner': None}, {'id': 1044, 'startDate': '1988-09-01', 'endDate': '1989-06-23', 'currentMatchday': None, 'winner': None}, {'id': 1045, 'startDate': '1987-08-27', 'endDate': '1988-05-20', 'currentMatchday': None, 'winner': None}, {'id': 1429, 'startDate': '1986-08-30', 'endDate': '1987-06-21', 'currentMatchday': None, 'winner': None}, {'id': 1047, 'startDate': '1985-08-29', 'endDate': '1986-04-18', 'currentMatchday': None, 'winner': None}, {'id': 1048, 'startDate': '1984-08-30', 'endDate': '1985-04-19', 'currentMatchday': None, 'winner': None}, {'id': 1049, 'startDate': '1983-09-01', 'endDate': '1984-04-27', 'currentMatchday': None, 'winner': None}, {'id': 1050, 'startDate': '1982-09-02', 'endDate': '1983-04-29', 'currentMatchday': None, 'winner': None}, {'id': 1046, 'startDate': '1981-09-17', 'endDate': '1982-04-23', 'currentMatchday': None, 'winner': None}, {'id': 1051, 'startDate': '1980-09-04', 'endDate': '1981-04-24', 'currentMatchday': None, 'winner': None}, {'id': 1052, 'startDate': '1979-09-06', 'endDate': '1980-05-16', 'currentMatchday': None, 'winner': None}, {'id': 1053, 'startDate': '1978-08-31', 'endDate': '1979-06-01', 'currentMatchday': None, 'winner': None}, {'id': 1054, 'startDate': '1977-09-01', 'endDate': '1978-05-05', 'currentMatchday': None, 'winner': None}, {'id': 1055, 'startDate': '1976-09-02', 'endDate': '1977-06-06', 'currentMatchday': None, 'winner': None}, {'id': 1056, 'startDate': '1975-09-04', 'endDate': '1976-05-14', 'currentMatchday': None, 'winner': None}, {'id': 1057, 'startDate': '1974-09-05', 'endDate': '1975-05-23', 'currentMatchday': None, 'winner': None}, {'id': 1058, 'startDate': '1973-08-30', 'endDate': '1974-05-18', 'currentMatchday': None, 'winner': None}, {'id': 1059, 'startDate': '1972-08-31', 'endDate': '1973-05-18', 'currentMatchday': None, 'winner': None}, {'id': 1060, 'startDate': '1971-09-02', 'endDate': '1972-05-12', 'currentMatchday': None, 'winner': None}, {'id': 1061, 'startDate': '1970-09-10', 'endDate': '1971-04-16', 'currentMatchday': None, 'winner': None}, {'id': 1062, 'startDate': '1969-09-11', 'endDate': '1970-04-17', 'currentMatchday': None, 'winner': None}, {'id': 1063, 'startDate': '1968-09-12', 'endDate': '1969-04-18', 'currentMatchday': None, 'winner': None}, {'id': 1428, 'startDate': '1967-09-09', 'endDate': '1968-04-28', 'currentMatchday': None, 'winner': None}, {'id': 1066, 'startDate': '1966-09-08', 'endDate': '1967-04-21', 'currentMatchday': None, 'winner': None}, {'id': 1067, 'startDate': '1965-09-02', 'endDate': '1966-04-01', 'currentMatchday': None, 'winner': None}, {'id': 1068, 'startDate': '1964-09-11', 'endDate': '1965-04-16', 'currentMatchday': None, 'winner': None}, {'id': 1069, 'startDate': '1963-09-13', 'endDate': '1964-04-24', 'currentMatchday': None, 'winner': None}, {'id': 1070, 'startDate': '1962-09-14', 'endDate': '1963-04-19', 'currentMatchday': None, 'winner': None}, {'id': 1071, 'startDate': '1961-08-31', 'endDate': '1962-03-30', 'currentMatchday': None, 'winner': None}, {'id': 1072, 'startDate': '1960-09-09', 'endDate': '1961-04-28', 'currentMatchday': None, 'winner': None}, {'id': 1073, 'startDate': '1959-09-11', 'endDate': '1960-04-15', 'currentMatchday': None, 'winner': None}, {'id': 1074, 'startDate': '1958-09-12', 'endDate': '1959-04-17', 'currentMatchday': None, 'winner': None}, {'id': 1075, 'startDate': '1957-09-13', 'endDate': '1958-05-02', 'currentMatchday': None, 'winner': None}, {'id': 1076, 'startDate': '1956-09-07', 'endDate': '1957-04-19', 'currentMatchday': None, 'winner': None}, {'id': 1077, 'startDate': '1955-09-09', 'endDate': '1956-04-20', 'currentMatchday': None, 'winner': None}, {'id': 1078, 'startDate': '1954-09-10', 'endDate': '1955-04-08', 'currentMatchday': None, 'winner': None}, {'id': 1079, 'startDate': '1953-09-11', 'endDate': '1954-04-23', 'currentMatchday': None, 'winner': None}, {'id': 1080, 'startDate': '1952-09-12', 'endDate': '1953-05-01', 'currentMatchday': None, 'winner': None}, {'id': 1081, 'startDate': '1951-09-07', 'endDate': '1952-04-11', 'currentMatchday': None, 'winner': None}, {'id': 1082, 'startDate': '1950-09-08', 'endDate': '1951-04-20', 'currentMatchday': None, 'winner': None}, {'id': 1083, 'startDate': '1949-09-02', 'endDate': '1950-04-21', 'currentMatchday': None, 'winner': None}, {'id': 1084, 'startDate': '1948-09-10', 'endDate': '1949-04-15', 'currentMatchday': None, 'winner': None}, {'id': 1085, 'startDate': '1947-09-19', 'endDate': '1948-04-09', 'currentMatchday': None, 'winner': None}, {'id': 1086, 'startDate': '1946-09-20', 'endDate': '1947-04-21', 'currentMatchday': None, 'winner': None}, {'id': 1087, 'startDate': '1945-09-21', 'endDate': '1946-03-29', 'currentMatchday': None, 'winner': None}, {'id': 1088, 'startDate': '1944-09-22', 'endDate': '1945-05-18', 'currentMatchday': None, 'winner': None}, {'id': 1089, 'startDate': '1943-09-24', 'endDate': '1944-04-07', 'currentMatchday': None, 'winner': None}, {'id': 1090, 'startDate': '1942-09-25', 'endDate': '1943-04-02', 'currentMatchday': None, 'winner': None}, {'id': 1091, 'startDate': '1941-09-26', 'endDate': '1942-04-03', 'currentMatchday': None, 'winner': None}, {'id': 1092, 'startDate': '1940-09-27', 'endDate': '1941-03-28', 'currentMatchday': None, 'winner': None}, {'id': 1093, 'startDate': '1939-12-01', 'endDate': '1940-04-26', 'currentMatchday': None, 'winner': None}, {'id': 1094, 'startDate': '1935-11-08', 'endDate': '1936-04-17', 'currentMatchday': None, 'winner': None}, {'id': 1095, 'startDate': '1934-11-30', 'endDate': '1935-04-26', 'currentMatchday': None, 'winner': None}, {'id': 1096, 'startDate': '1933-11-03', 'endDate': '1934-03-02', 'currentMatchday': None, 'winner': None}, {'id': 1097, 'startDate': '1932-11-25', 'endDate': '1933-03-26', 'currentMatchday': None, 'winner': None}, {'id': 1098, 'startDate': '1931-11-20', 'endDate': '1932-04-01', 'currentMatchday': None, 'winner': None}, {'id': 1099, 'startDate': '1930-12-05', 'endDate': '1931-04-03', 'currentMatchday': None, 'winner': None}, {'id': 1100, 'startDate': '1929-11-29', 'endDate': '1930-03-28', 'currentMatchday': None, 'winner': None}, {'id': 1101, 'startDate': '1928-02-08', 'endDate': '1929-06-28', 'currentMatchday': None, 'winner': None}]
lastUpdated: 2024-09-13T16:52:33Z

In [ ]:
cursor.execute("""
    INSERT INTO dim_competicion  (id_competicion, nombre, codigo , pais)
    VALUES (?, ?, ?, ?)
""", 
    comp['id'], 
    comp['name'], 
    comp['code'], 
    comp['area']['name']
    )
conn.commit()
print("Informacion de la competicion subida al Sql Server Correctamente")

In [6]:
URL = 'https://api.football-data.org/v4/competitions/2014/matches' # se considera el ID en la URL para obtener los partidos de la Liga Española

credenciales = {'X-Auth-Token': API_KEY}

response = requests.get(URL,headers=credenciales)
data = response.json()

In [7]:
data

{'filters': {'season': '2025'},
 'resultSet': {'count': 380,
  'first': '2025-08-15',
  'last': '2026-05-24',
  'played': 275},
 'competition': {'id': 2014,
  'name': 'Primera Division',
  'code': 'PD',
  'type': 'LEAGUE',
  'emblem': 'https://crests.football-data.org/laliga.png'},
 'matches': [{'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544214,
   'utcDate': '2025-08-15T17:00:00Z',
   'status': 'FINISHED',
   'matchday': 1,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 298,
    'name': 'Girona FC',
    'shortName': 'Girona',
    'tla': 'GIR',
    'crest': 'https://crests.football-data.org/298.png'},
   'awayTeam': {'id': 87,
    'name': 'Rayo Vallecano de Madrid',
    'shortName': 'Rayo Vallecano',
    'tla': 'RAY',
    'crest': 'https://crests.football-data.org/87.png'},
   'score': {'winner': 'AWAY_TEAM',
    'duration': 'REGULAR',
    'fullTime': {'home': 1, 'away': 3},
    'halfTime': {'home': 0, 'away': 3}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 80747,
     'name': 'Javier Alberola Rojas',
     'type': 'REFEREE',
     'nationality': None}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544220,
   'utcDate': '2025-08-15T19:30:00Z',
   'status': 'FINISHED',
   'matchday': 1,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 94,
    'name': 'Villarreal CF',
    'shortName': 'Villarreal',
    'tla': 'VIL',
    'crest': 'https://crests.football-data.org/94.png'},
   'awayTeam': {'id': 1048,
    'name': 'Real Oviedo',
    'shortName': 'Real Oviedo',
    'tla': 'OVI',
    'crest': 'https://crests.football-data.org/1048.png'},
   'score': {'winner': 'HOME_TEAM',
    'duration': 'REGULAR',
    'fullTime': {'home': 2, 'away': 0},
    'halfTime': {'home': 2, 'away': 0}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 215569,
     'name': 'Alejandro Muñiz Ruiz',
     'type': 'REFEREE',
     'nationality': 'Spain'}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544216,
   'utcDate': '2025-08-16T17:30:00Z',
   'status': 'FINISHED',
   'matchday': 1,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 89,
    'name': 'RCD Mallorca',
    'shortName': 'Mallorca',
    'tla': 'MAL',
    'crest': 'https://crests.football-data.org/89.png'},
   'awayTeam': {'id': 81,
    'name': 'FC Barcelona',
    'shortName': 'Barça',
    'tla': 'FCB',
    'crest': 'https://crests.football-data.org/81.png'},
   'score': {'winner': 'AWAY_TEAM',
    'duration': 'REGULAR',
    'fullTime': {'home': 0, 'away': 3},
    'halfTime': {'home': 0, 'away': 2}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 206223,
     'name': 'José Munuera Montero',
     'type': 'REFEREE',
     'nationality': 'Spain'}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544211,
   'utcDate': '2025-08-16T19:30:00Z',
   'status': 'FINISHED',
   'matchday': 1,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 263,
    'name': 'Deportivo Alavés',
    'shortName': 'Alavés',
    'tla': 'ALA',
    'crest': 'https://crests.football-data.org/263.png'},
   'awayTeam': {'id': 88,
    'name': 'Levante UD',
    'shortName': 'Levante',
    'tla': 'LEV',
    'crest': 'https://crests.football-data.org/88.png'},
   'score': {'winner': 'HOME_TEAM',
    'duration': 'REGULAR',
    'fullTime': {'home': 2, 'away': 1},
    'halfTime': {'home': 1, 'away': 0}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 214573,
     'name': 'Miguel Sesma Espinosa',
     'type': 'REFEREE',
     'nationality': 'Spain'}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544219,
   'utcDate': '2025-08-16T19:30:00Z',
   'status': 'FINISHED',
   'matchday': 1,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 95,
    'name': 'Valencia CF',
    'shortName': 'Valencia',
    'tla': 'VAL',
    'crest': 'https://crests.football-data.org/95.png'},
   'awayTeam': {'id': 92,
    'name': 'Real Sociedad de Fútbol',
    'shortName': 'Real Sociedad',
    'tla': 'RSO',
    'crest': 'https://crests.football-data.org/92.png'},
   'score': {'winner': 'DRAW',
    'duration': 'REGULAR',
    'fullTime': {'home': 1, 'away': 1},
    'halfTime': {'home': 0, 'away': 0}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 207080,
     'name': 'José Sánchez Martínez',
     'type': 'REFEREE',
     'nationality': 'Spain'}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544213,
   'utcDate': '2025-08-17T15:00:00Z',
   'status': 'FINISHED',
   'matchday': 1,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 558,
    'name': 'RC Celta de Vigo',
    'shortName': 'Celta',
    'tla': 'CEL',
    'crest': 'https://crests.football-data.org/558.png'},
   'awayTeam': {'id': 82,
    'name': 'Getafe CF',
    'shortName': 'Getafe',
    'tla': 'GET',
    'crest': 'https://crests.football-data.org/82.png'},
   'score': {'winner': 'AWAY_TEAM',
    'duration': 'REGULAR',
    'fullTime': {'home': 0, 'away': 2},
    'halfTime': {'home': 0, 'away': 0}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': []},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544212,
   'utcDate': '2025-08-17T17:30:00Z',
   'status': 'FINISHED',
   'matchday': 1,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 77,
    'name': 'Athletic Club',
    'shortName': 'Athletic',
    'tla': 'ATH',
    'crest': 'https://crests.football-data.org/77.png'},
   'awayTeam': {'id': 559,
    'name': 'Sevilla FC',
    'shortName': 'Sevilla FC',
    'tla': 'SEV',
    'crest': 'https://crests.football-data.org/559.png'},
   'score': {'winner': 'HOME_TEAM',
    'duration': 'REGULAR',
    'fullTime': {'home': 3, 'away': 2},
    'halfTime': {'home': 2, 'away': 0}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': []},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544215,
   'utcDate': '2025-08-17T19:30:00Z',
   'status': 'FINISHED',
   'matchday': 1,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 80,
    'name': 'RCD Espanyol de Barcelona',
    'shortName': 'Espanyol',
    'tla': 'ESP',
    'crest': 'https://crests.football-data.org/80.png'},
   'awayTeam': {'id': 78,
    'name': 'Club Atlético de Madrid',
    'shortName': 'Atleti',
    'tla': 'ATL',
    'crest': 'https://crests.football-data.org/78.png'},
   'score': {'winner': 'HOME_TEAM',
    'duration': 'REGULAR',
    'fullTime': {'home': 2, 'away': 1},
    'halfTime': {'home': 0, 'away': 1}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': []},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544217,
   'utcDate': '2025-08-18T19:00:00Z',
   'status': 'FINISHED',
   'matchday': 1,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 285,
    'name': 'Elche CF',
    'shortName': 'Elche',
    'tla': 'ELC',
    'crest': 'https://crests.football-data.org/285.png'},
   'awayTeam': {'id': 90,
    'name': 'Real Betis Balompié',
    'shortName': 'Real Betis',
    'tla': 'BET',
    'crest': 'https://crests.football-data.org/90.png'},
   'score': {'winner': 'DRAW',
    'duration': 'REGULAR',
    'fullTime': {'home': 1, 'away': 1},
    'halfTime': {'home': 0, 'away': 1}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 56995,
     'name': 'Víctor García Verdura',
     'type': 'REFEREE',
     'nationality': 'Spain'}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544218,
   'utcDate': '2025-08-19T19:00:00Z',
   'status': 'FINISHED',
   'matchday': 1,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 86,
    'name': 'Real Madrid CF',
    'shortName': 'Real Madrid',
    'tla': 'RMA',
    'crest': 'https://crests.football-data.org/86.png'},
   'awayTeam': {'id': 79,
    'name': 'CA Osasuna',
    'shortName': 'Osasuna',
    'tla': 'OSA',
    'crest': 'https://crests.football-data.org/79.png'},
   'score': {'winner': 'HOME_TEAM',
    'duration': 'REGULAR',
    'fullTime': {'home': 1, 'away': 0},
    'halfTime': {'home': 0, 'away': 0}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 206205,
     'name': 'Adrián Cordero Vega',
     'type': 'REFEREE',
     'nationality': 'Spain'}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544225,
   'utcDate': '2025-08-22T19:30:00Z',
   'status': 'FINISHED',
   'matchday': 2,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 90,
    'name': 'Real Betis Balompié',
    'shortName': 'Real Betis',
    'tla': 'BET',
    'crest': 'https://crests.football-data.org/90.png'},
   'awayTeam': {'id': 263,
    'name': 'Deportivo Alavés',
    'shortName': 'Alavés',
    'tla': 'ALA',
    'crest': 'https://crests.football-data.org/263.png'},
   'score': {'winner': 'HOME_TEAM',
    'duration': 'REGULAR',
    'fullTime': {'home': 1, 'away': 0},
    'halfTime': {'home': 1, 'away': 0}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 207048,
     'name': 'Miguel Ortiz Arias',
     'type': 'REFEREE',
     'nationality': 'Spain'}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544227,
   'utcDate': '2025-08-23T15:00:00Z',
   'status': 'FINISHED',
   'matchday': 2,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 89,
    'name': 'RCD Mallorca',
    'shortName': 'Mallorca',
    'tla': 'MAL',
    'crest': 'https://crests.football-data.org/89.png'},
   'awayTeam': {'id': 558,
    'name': 'RC Celta de Vigo',
    'shortName': 'Celta',
    'tla': 'CEL',
    'crest': 'https://crests.football-data.org/558.png'},
   'score': {'winner': 'DRAW',
    'duration': 'REGULAR',
    'fullTime': {'home': 1, 'away': 1},
    'halfTime': {'home': 0, 'away': 1}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 215507,
     'name': 'José Luis Guzmán Mansilla',
     'type': 'REFEREE',
     'nationality': 'Spain'}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544222,
   'utcDate': '2025-08-23T17:30:00Z',
   'status': 'FINISHED',
   'matchday': 2,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 78,
    'name': 'Club Atlético de Madrid',
    'shortName': 'Atleti',
    'tla': 'ATL',
    'crest': 'https://crests.football-data.org/78.png'},
   'awayTeam': {'id': 285,
    'name': 'Elche CF',
    'shortName': 'Elche',
    'tla': 'ELC',
    'crest': 'https://crests.football-data.org/285.png'},
   'score': {'winner': 'DRAW',
    'duration': 'REGULAR',
    'fullTime': {'home': 1, 'away': 1},
    'halfTime': {'home': 1, 'away': 1}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 207113,
     'name': 'César Soto Grado',
     'type': 'REFEREE',
     'nationality': 'Spain'}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544226,
   'utcDate': '2025-08-23T19:30:00Z',
   'status': 'FINISHED',
   'matchday': 2,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 88,
    'name': 'Levante UD',
    'shortName': 'Levante',
    'tla': 'LEV',
    'crest': 'https://crests.football-data.org/88.png'},
   'awayTeam': {'id': 81,
    'name': 'FC Barcelona',
    'shortName': 'Barça',
    'tla': 'FCB',
    'crest': 'https://crests.football-data.org/81.png'},
   'score': {'winner': 'AWAY_TEAM',
    'duration': 'REGULAR',
    'fullTime': {'home': 2, 'away': 3},
    'halfTime': {'home': 2, 'away': 0}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 206208,
     'name': 'Alejandro Hernández Hernández',
     'type': 'REFEREE',
     'nationality': 'Spain'}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544223,
   'utcDate': '2025-08-24T15:00:00Z',
   'status': 'FINISHED',
   'matchday': 2,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 79,
    'name': 'CA Osasuna',
    'shortName': 'Osasuna',
    'tla': 'OSA',
    'crest': 'https://crests.football-data.org/79.png'},
   'awayTeam': {'id': 95,
    'name': 'Valencia CF',
    'shortName': 'Valencia',
    'tla': 'VAL',
    'crest': 'https://crests.football-data.org/95.png'},
   'score': {'winner': 'HOME_TEAM',
    'duration': 'REGULAR',
    'fullTime': {'home': 1, 'away': 0},
    'halfTime': {'home': 1, 'away': 0}},
   'odds': {'msg': 'Activate Odds-Package in User-Panel to retrieve odds.'},
   'referees': [{'id': 206211,
     'name': 'Jesús Gil Manzano',
     'type': 'REFEREE',
     'nationality': 'Spain'}]},
  {'area': {'id': 2224,
    'name': 'Spain',
    'code': 'ESP',
    'flag': 'https://crests.football-data.org/760.svg'},
   'competition': {'id': 2014,
    'name': 'Primera Division',
    'code': 'PD',
    'type': 'LEAGUE',
    'emblem': 'https://crests.football-data.org/laliga.png'},
   'season': {'id': 2429,
    'startDate': '2025-08-17',
    'endDate': '2026-05-24',
    'currentMatchday': 28,
    'winner': None},
   'id': 544228,
   'utcDate': '2025-08-24T17:30:00Z',
   'status': 'FINISHED',
   'matchday': 2,
   'stage': 'REGULAR_SEASON',
   'group': None,
   'lastUpdated': '2026-03-14T00:21:02Z',
   'homeTeam': {'id': 92,
    'name': 'Real Sociedad de Fútbol',
    'shortName': 'Real Sociedad',
    'tla': 'RSO',
    'crest': 'https://crests.football-data.org/92.png'},
   'awayTeam': {'id': 80,
    'name': 'RCD Espanyol de Barcelona',
    'shortName': 'Espanyol',
    'tla': 'ESP',

In [8]:
print(json.dumps(data['matches'][0], indent=2))

{
  "area": {
    "id": 2224,
    "name": "Spain",
    "code": "ESP",
    "flag": "https://crests.football-data.org/760.svg"
  },
  "competition": {
    "id": 2014,
    "name": "Primera Division",
    "code": "PD",
    "type": "LEAGUE",
    "emblem": "https://crests.football-data.org/laliga.png"
  },
  "season": {
    "id": 2429,
    "startDate": "2025-08-17",
    "endDate": "2026-05-24",
    "currentMatchday": 28,
    "winner": null
  },
  "id": 544214,
  "utcDate": "2025-08-15T17:00:00Z",
  "status": "FINISHED",
  "matchday": 1,
  "stage": "REGULAR_SEASON",
  "group": null,
  "lastUpdated": "2026-03-14T00:21:02Z",
  "homeTeam": {
    "id": 298,
    "name": "Girona FC",
    "shortName": "Girona",
    "tla": "GIR",
    "crest": "https://crests.football-data.org/298.png"
  },
  "awayTeam": {
    "id": 87,
    "name": "Rayo Vallecano de Madrid",
    "shortName": "Rayo Vallecano",
    "tla": "RAY",
    "crest": "https://crests.football-data.org/87.png"
  },
  "score": {
    "winner": "AWAY_TEAM",
    "duration": "REGULAR",
    "fullTime": {
      "home": 1,
      "away": 3
    },
    "halfTime": {
      "home": 0,
      "away": 3
    }
  },
  "odds": {
    "msg": "Activate Odds-Package in User-Panel to retrieve odds."
  },
  "referees": [
    {
      "id": 80747,
      "name": "Javier Alberola Rojas",
      "type": "REFEREE",
      "nationality": null
    }
  ]
}

In [9]:
for partido in data['matches'][:5]:
    print(f'Jornada: {partido["matchday"]} | {partido["homeTeam"]["name"]} vs {partido["awayTeam"]["name"]} | -> {partido["score"]["fullTime"]["home"]} - {partido["score"]["fullTime"]["away"]}')

Jornada: 1 | Girona FC vs Rayo Vallecano de Madrid | -> 1 - 3
Jornada: 1 | Villarreal CF vs Real Oviedo | -> 2 - 0
Jornada: 1 | RCD Mallorca vs FC Barcelona | -> 0 - 3
Jornada: 1 | Deportivo Alavés vs Levante UD | -> 2 - 1
Jornada: 1 | Valencia CF vs Real Sociedad de Fútbol | -> 1 - 1

In [13]:
for partido in data['matches']:

    id_partido  = partido['id']
    fecha       = partido['utcDate']
    local       = partido['homeTeam']['name']
    visitante   = partido['awayTeam']['name']
    goles_local = partido['score']['fullTime']['home']
    goles_visita = partido['score']['fullTime']['away']

    cursor.execute("""
        INSERT INTO fact_partido (id_partido, fecha, local, visitante, goles_local, goles_visitante)
        VALUES (?, ?, ?, ?, ?, ?)
    """, id_partido, fecha, local, visitante, goles_local, goles_visita)

conn.commit()

ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'local'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'visitante'. (207); [42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared. (8180)")

## Informacion de los equipos Españoles

In [12]:
URL = 'https://api.football-data.org/v4/competitions/2014/teams'
token = API_KEY
credenciales = {'X-Auth-Token': token}

response = requests.get(URL,headers=credenciales)
data = response.json()

In [13]:
for key, value in data.items():
    print(f"{key}: {value}")

count: 20
filters: {'season': '2025'}
competition: {'id': 2014, 'name': 'Primera Division', 'code': 'PD', 'type': 'LEAGUE', 'emblem': 'https://crests.football-data.org/laliga.png'}
season: {'id': 2429, 'startDate': '2025-08-17', 'endDate': '2026-05-24', 'currentMatchday': 28, 'winner': None}

In [14]:
print(json.dumps(data['teams'][0], indent=2))

{
  "area": {
    "id": 2224,
    "name": "Spain",
    "code": "ESP",
    "flag": "https://crests.football-data.org/760.svg"
  },
  "id": 77,
  "name": "Athletic Club",
  "shortName": "Athletic",
  "tla": "ATH",
  "crest": "https://crests.football-data.org/77.png",
  "address": "Ibaigane, Alameda Mazarredo, 23 Bilbao 48009",
  "website": "http://www.athletic-club.eus",
  "founded": 1898,
  "clubColors": "Red / White / Black",
  "venue": "San Mam\u00e9s",
  "runningCompetitions": [
    {
      "id": 2014,
      "name": "Primera Division",
      "code": "PD",
      "type": "LEAGUE",
      "emblem": "https://crests.football-data.org/laliga.png"
    },
    {
      "id": 2001,
      "name": "UEFA Champions League",
      "code": "CL",
      "type": "CUP",
      "emblem": "https://crests.football-data.org/CL.png"
    }
  ],
  "coach": {
    "id": 15873,
    "firstName": "",
    "lastName": "Ernesto Valverde",
    "name": "Ernesto Valverde",
    "dateOfBirth": "1964-02-09",
    "nationality": "Spain",
    "contract": {
      "start": "2022-07",
      "until": "2026-06"
    }
  },
  "squad": [
    {
      "id": 32570,
      "name": "Unai Sim\u00f3n",
      "position": "Goalkeeper",
      "dateOfBirth": "1997-06-11",
      "nationality": "Spain"
    },
    {
      "id": 203459,
      "name": "\u00c1lex Padilla",
      "position": "Goalkeeper",
      "dateOfBirth": "2003-09-01",
      "nationality": "Spain"
    },
    {
      "id": 286275,
      "name": "Mikel Santos",
      "position": "Goalkeeper",
      "dateOfBirth": "2004-11-01",
      "nationality": "Spain"
    },
    {
      "id": 217432,
      "name": "Unai Egu\u00edluz",
      "position": "Defence",
      "dateOfBirth": "2002-03-19",
      "nationality": "Spain"
    },
    {
      "id": 276865,
      "name": "Aimar Du\u00f1abeitia",
      "position": "Defence",
      "dateOfBirth": "2003-02-26",
      "nationality": "Spain"
    },
    {
      "id": 276982,
      "name": "Ander Izagirre",
      "position": "Defence",
      "dateOfBirth": "2003-06-28",
      "nationality": "Spain"
    },
    {
      "id": 283817,
      "name": "Jon de Luis",
      "position": "Defence",
      "dateOfBirth": "2003-08-05",
      "nationality": "Spain"
    },
    {
      "id": 286606,
      "name": "Iker Monreal",
      "position": "Defence",
      "dateOfBirth": "2005-07-03",
      "nationality": "Spain"
    },
    {
      "id": 278297,
      "name": "Alejandro Rego",
      "position": "Midfield",
      "dateOfBirth": "2003-06-11",
      "nationality": "Spain"
    },
    {
      "id": 287081,
      "name": "Ibon S\u00e1nchez",
      "position": "Midfield",
      "dateOfBirth": "2004-03-08",
      "nationality": "Spain"
    },
    {
      "id": 288898,
      "name": "Selton S\u00e1nchez",
      "position": "Midfield",
      "dateOfBirth": "2007-02-20",
      "nationality": "Spain"
    },
    {
      "id": 189820,
      "name": "Urko Izeta",
      "position": "Offence",
      "dateOfBirth": "1999-09-29",
      "nationality": "Spain"
    },
    {
      "id": 231471,
      "name": "Endika Buj\u00e1n",
      "position": "Offence",
      "dateOfBirth": "2003-01-16",
      "nationality": "Spain"
    },
    {
      "id": 287080,
      "name": "Adri\u00e1n P\u00e9rez",
      "position": "Offence",
      "dateOfBirth": "2006-10-25",
      "nationality": "Spain"
    },
    {
      "id": 289113,
      "name": "Asier Hierro",
      "position": "Offence",
      "dateOfBirth": "2005-05-06",
      "nationality": "Spain"
    },
    {
      "id": 289717,
      "name": "\u00c9der Garc\u00eda",
      "position": "Offence",
      "dateOfBirth": "2004-01-04",
      "nationality": "Spain"
    },
    {
      "id": 291751,
      "name": "Elijah Gift",
      "position": "Offence",
      "dateOfBirth": "2006-06-11",
      "nationality": "Spain"
    },
    {
      "id": 172027,
      "name": "Nico Serrano",
      "position": "Left Winger",
      "dateOfBirth": "2003-03-05",
      "nationality": "Spain"
    },
    {
      "id": 168663,
      "name": "Benat Prados",
      "position": "Central Midfield",
      "dateOfBirth": "2001-02-08",
      "nationality": "Spain"
    },
    {
      "id": 157135,
      "name": "Nico Williams",
      "position": "Left Winger",
      "dateOfBirth": "2002-07-12",
      "nationality": "Spain"
    },
    {
      "id": 151439,
      "name": "Aitor Paredes Casamichana",
      "position": "Centre-Back",
      "dateOfBirth": "2000-04-29",
      "nationality": "Spain"
    },
    {
      "id": 136000,
      "name": "Jes\u00fas Areso",
      "position": "Right-Back",
      "dateOfBirth": "1999-07-02",
      "nationality": "Spain"
    },
    {
      "id": 126878,
      "name": "Oihan Sancet",
      "position": "Attacking Midfield",
      "dateOfBirth": "2000-04-25",
      "nationality": "Spain"
    },
    {
      "id": 101870,
      "name": "Roberto Navarro",
      "position": "Attacking Midfield",
      "dateOfBirth": "2002-04-12",
      "nationality": "Spain"
    },
    {
      "id": 96868,
      "name": "Mikel Vesga",
      "position": "Defensive Midfield",
      "dateOfBirth": "1993-04-08",
      "nationality": "Spain"
    },
    {
      "id": 81565,
      "name": "Gorka Guruzeta",
      "position": "Centre-Forward",
      "dateOfBirth": "1996-09-12",
      "nationality": "Spain"
    },
    {
      "id": 33091,
      "name": "Andoni Gorosabel",
      "position": "Right-Back",
      "dateOfBirth": "1996-08-04",
      "nationality": "Spain"
    },
    {
      "id": 32629,
      "name": "I\u00f1aki Williams",
      "position": "Right Winger",
      "dateOfBirth": "1994-06-15",
      "nationality": "Ghana"
    },
    {
      "id": 32618,
      "name": "Daniel Vivian",
      "position": "Centre-Back",
      "dateOfBirth": "1999-07-05",
      "nationality": "Spain"
    },
    {
      "id": 32581,
      "name": "I\u00f1igo Lekue",
      "position": "Right-Back",
      "dateOfBirth": "1993-05-04",
      "nationality": "Spain"
    },
    {
      "id": 32579,
      "name": "Yeray \u00c1lvarez",
      "position": "Centre-Back",
      "dateOfBirth": "1995-01-24",
      "nationality": "Spain"
    },
    {
      "id": 32481,
      "name": "Ruiz de Galarreta",
      "position": "Central Midfield",
      "dateOfBirth": "1993-08-06",
      "nationality": "Spain"
    },
    {
      "id": 8479,
      "name": "Yuri Berchiche",
      "position": "Left-Back",
      "dateOfBirth": "1990-02-10",
      "nationality": "Spain"
    },
    {
      "id": 7884,
      "name": "Aymeric Laporte",
      "position": "Centre-Back",
      "dateOfBirth": "1994-05-27",
      "nationality": "Spain"
    },
    {
      "id": 2294,
      "name": "\u00c1lex Berenguer",
      "position": "Left Winger",
      "dateOfBirth": "1995-07-04",
      "nationality": "Spain"
    },
    {
      "id": 261580,
      "name": "Sannadi",
      "position": "Centre-Forward",
      "dateOfBirth": "2001-02-01",
      "nationality": "Spain"
    },
    {
      "id": 246633,
      "name": "Adama Boiro",
      "position": "Left-Back",
      "dateOfBirth": "2002-06-22",
      "nationality": "Spain"
    },
    {
      "id": 244599,
      "name": "Mikel Jauregizar",
      "position": "Central Midfield",
      "dateOfBirth": "2003-11-13",
      "nationality": "Spain"
    },
    {
      "id": 202335,
      "name": "Unai Gomez",
      "position": "Attacking Midfield",
      "dateOfBirth": "2003-05-25",
      "nationality": "Spain"
    }
  ],
  "staff": [],
  "lastUpdated": "2022-03-06T09:31:27Z"
}

In [16]:
for equipo in data['teams']:
    id_equipo = equipo['id']
    nombre = equipo['name']
    nombre_corto = equipo['shortName']
    estadio = equipo['venue']
    cursor.execute("""
        INSERT INTO dim_equipo (id_equipo, nombre, nombre_corto, estadio)
        VALUES (?, ?, ?, ?)
    """, id_equipo, nombre, nombre_corto, estadio)
    conn.commit()

In [25]:
df_equipos = pd.read_sql_query("SELECT * FROM dim_equipo", conn)
df_equipos

C:\Users\brger\AppData\Local\Temp\ipykernel_15200\2982039710.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_equipos = pd.read_sql_query("SELECT * FROM dim_equipo", conn)

,id_equipo,nombre,nombre_corto,estadio
0,77,Athletic Club,Athletic,San Mamés
1,78,Club Atlético de Madrid,Atleti,Estadio Wanda Metropolitano
2,79,CA Osasuna,Osasuna,Estadio El Sadar
3,80,RCD Espanyol de Barcelona,Espanyol,RCDE Stadium
4,81,FC Barcelona,Barça,Camp Nou
5,82,Getafe CF,Getafe,Coliseum Alfonso Pérez
6,86,Real Madrid CF,Real Madrid,Estadio Santiago Bernabéu
7,87,Rayo Vallecano de Madrid,Rayo Vallecano,Estadio del Rayo Vallecano
8,88,Levante UD,Levante,Estadio Ciudad de Valencia
9,89,RCD Mallorca,Mallorca,Iberostar Estadi
10,90,Real Betis Balompié,Real Betis,Estadio Benito Villamarín
11,92,Real Sociedad de Fútbol,Real Sociedad,Estadio Municipal de Anoeta
12,94,Villarreal CF,Villarreal,Estadio de la Cerámica
13,95,Valencia CF,Valencia,Estadio de Mestalla
14,263,Deportivo Alavés,Alavés,Estadio de Mendizorroza
15,285,Elche CF,Elche,Estadio Manuel Martínez Valero
16,298,Girona FC,Girona,Estadi Municipal de Montilivi
17,558,RC Celta de Vigo,Celta,Estadio de Balaídos
18,559,Sevilla FC,Sevilla FC,Estadio Ramón Sánchez Pizjuán
19,1048,Real Oviedo,Real Oviedo,Estadio Nuevo Carlos Tartiere

## Informacion de los partidos de la Liga

In [31]:
URL = 'https://api.football-data.org/v4/competitions/2014/matches'
credenciales = {'X-Auth-Token': API_KEY}
response = requests.get(URL,headers=credenciales)
partidos = response.json()

In [27]:
json.dumps(partidos['matches'][0], indent=2)

'{\n  "area": {\n    "id": 2224,\n    "name": "Spain",\n    "code": "ESP",\n    "flag": "https://crests.football-data.org/760.svg"\n  },\n  "competition": {\n    "id": 2014,\n    "name": "Primera Division",\n    "code": "PD",\n    "type": "LEAGUE",\n    "emblem": "https://crests.football-data.org/laliga.png"\n  },\n  "season": {\n    "id": 2429,\n    "startDate": "2025-08-17",\n    "endDate": "2026-05-24",\n    "currentMatchday": 28,\n    "winner": null\n  },\n  "id": 544214,\n  "utcDate": "2025-08-15T17:00:00Z",\n  "status": "FINISHED",\n  "matchday": 1,\n  "stage": "REGULAR_SEASON",\n  "group": null,\n  "lastUpdated": "2026-03-14T00:21:02Z",\n  "homeTeam": {\n    "id": 298,\n    "name": "Girona FC",\n    "shortName": "Girona",\n    "tla": "GIR",\n    "crest": "https://crests.football-data.org/298.png"\n  },\n  "awayTeam": {\n    "id": 87,\n    "name": "Rayo Vallecano de Madrid",\n    "shortName": "Rayo Vallecano",\n    "tla": "RAY",\n    "crest": "https://crests.football-data.org/87.png"\n  },\n  "score": {\n    "winner": "AWAY_TEAM",\n    "duration": "REGULAR",\n    "fullTime": {\n      "home": 1,\n      "away": 3\n    },\n    "halfTime": {\n      "home": 0,\n      "away": 3\n    }\n  },\n  "odds": {\n    "msg": "Activate Odds-Package in User-Panel to retrieve odds."\n  },\n  "referees": [\n    {\n      "id": 80747,\n      "name": "Javier Alberola Rojas",\n      "type": "REFEREE",\n      "nationality": null\n    }\n  ]\n}'

In [33]:
cursor = conn.cursor()

mapa = {'HOME_TEAM': 'H', 'AWAY_TEAM': 'A', 'DRAW': 'D'}

for partido in partidos['matches']:
    if partido['status'] != 'FINISHED':
        continue

    temporada       = '2025/26'
    fecha           = partido['utcDate'][:10]
    jornada         = partido['matchday']
    id_local        = partido['homeTeam']['id']
    id_visitante    = partido['awayTeam']['id']
    goles_local     = partido['score']['fullTime']['home']
    goles_visitante = partido['score']['fullTime']['away']
    goles_ht_local  = partido['score']['halfTime']['home']
    goles_ht_visit  = partido['score']['halfTime']['away']
    resultado       = mapa[partido['score']['winner']]

    cursor.execute("""
        INSERT INTO fact_partido (
            temporada, fecha, jornada,
            id_equipo_local, id_equipo_visitante,
            goles_local, goles_visitante, resultado,
            goles_ht_local, goles_ht_visitante,
            fuente
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, temporada, fecha, jornada,
         id_local, id_visitante,
         goles_local, goles_visitante, resultado,
         goles_ht_local, goles_ht_visit,
         'API')

conn.commit()
print("✅ fact_partido cargada")

✅ fact_partido cargada

## Informacion por Jornada

In [ ]:
URL = 'https://api.football-data.org//v4/competitions/2014/standings?matchday=1'
credenciales = {'X-Auth-Token': API_KEY}
response = requests.get(URL,headers=credenciales)
standings = response.json()

In [39]:
for equipo in standings:
    print(equipo)

{'position': 1, 'team': {'id': 81, 'name': 'FC Barcelona', 'shortName': 'Barça', 'tla': 'FCB', 'crest': 'https://crests.football-data.org/81.png'}, 'playedGames': 27, 'form': None, 'won': 22, 'draw': 1, 'lost': 4, 'points': 67, 'goalsFor': 72, 'goalsAgainst': 26, 'goalDifference': 46}
{'position': 2, 'team': {'id': 86, 'name': 'Real Madrid CF', 'shortName': 'Real Madrid', 'tla': 'RMA', 'crest': 'https://crests.football-data.org/86.png'}, 'playedGames': 28, 'form': None, 'won': 21, 'draw': 3, 'lost': 4, 'points': 66, 'goalsFor': 60, 'goalsAgainst': 24, 'goalDifference': 36}
{'position': 3, 'team': {'id': 78, 'name': 'Club Atlético de Madrid', 'shortName': 'Atleti', 'tla': 'ATL', 'crest': 'https://crests.football-data.org/78.png'}, 'playedGames': 28, 'form': None, 'won': 17, 'draw': 6, 'lost': 5, 'points': 57, 'goalsFor': 47, 'goalsAgainst': 25, 'goalDifference': 22}
{'position': 4, 'team': {'id': 94, 'name': 'Villarreal CF', 'shortName': 'Villarreal', 'tla': 'VIL', 'crest': 'https://crests.football-data.org/94.png'}, 'playedGames': 28, 'form': None, 'won': 17, 'draw': 4, 'lost': 7, 'points': 55, 'goalsFor': 51, 'goalsAgainst': 33, 'goalDifference': 18}
{'position': 5, 'team': {'id': 90, 'name': 'Real Betis Balompié', 'shortName': 'Real Betis', 'tla': 'BET', 'crest': 'https://crests.football-data.org/90.png'}, 'playedGames': 27, 'form': None, 'won': 11, 'draw': 10, 'lost': 6, 'points': 43, 'goalsFor': 42, 'goalsAgainst': 34, 'goalDifference': 8}
{'position': 6, 'team': {'id': 558, 'name': 'RC Celta de Vigo', 'shortName': 'Celta', 'tla': 'CEL', 'crest': 'https://crests.football-data.org/558.png'}, 'playedGames': 27, 'form': None, 'won': 10, 'draw': 10, 'lost': 7, 'points': 40, 'goalsFor': 37, 'goalsAgainst': 30, 'goalDifference': 7}
{'position': 7, 'team': {'id': 80, 'name': 'RCD Espanyol de Barcelona', 'shortName': 'Espanyol', 'tla': 'ESP', 'crest': 'https://crests.football-data.org/80.png'}, 'playedGames': 27, 'form': None, 'won': 10, 'draw': 7, 'lost': 10, 'points': 37, 'goalsFor': 34, 'goalsAgainst': 40, 'goalDifference': -6}
{'position': 8, 'team': {'id': 92, 'name': 'Real Sociedad de Fútbol', 'shortName': 'Real Sociedad', 'tla': 'RSO', 'crest': 'https://crests.football-data.org/92.png'}, 'playedGames': 27, 'form': None, 'won': 9, 'draw': 8, 'lost': 10, 'points': 35, 'goalsFor': 40, 'goalsAgainst': 41, 'goalDifference': -1}
{'position': 9, 'team': {'id': 82, 'name': 'Getafe CF', 'shortName': 'Getafe', 'tla': 'GET', 'crest': 'https://crests.football-data.org/82.png'}, 'playedGames': 28, 'form': None, 'won': 10, 'draw': 5, 'lost': 13, 'points': 35, 'goalsFor': 23, 'goalsAgainst': 30, 'goalDifference': -7}
{'position': 10, 'team': {'id': 77, 'name': 'Athletic Club', 'shortName': 'Athletic', 'tla': 'ATH', 'crest': 'https://crests.football-data.org/77.png'}, 'playedGames': 28, 'form': None, 'won': 10, 'draw': 5, 'lost': 13, 'points': 35, 'goalsFor': 30, 'goalsAgainst': 40, 'goalDifference': -10}
{'position': 11, 'team': {'id': 79, 'name': 'CA Osasuna', 'shortName': 'Osasuna', 'tla': 'OSA', 'crest': 'https://crests.football-data.org/79.png'}, 'playedGames': 27, 'form': None, 'won': 9, 'draw': 7, 'lost': 11, 'points': 34, 'goalsFor': 32, 'goalsAgainst': 32, 'goalDifference': 0}
{'position': 12, 'team': {'id': 298, 'name': 'Girona FC', 'shortName': 'Girona', 'tla': 'GIR', 'crest': 'https://crests.football-data.org/298.png'}, 'playedGames': 28, 'form': None, 'won': 8, 'draw': 10, 'lost': 10, 'points': 34, 'goalsFor': 31, 'goalsAgainst': 43, 'goalDifference': -12}
{'position': 13, 'team': {'id': 95, 'name': 'Valencia CF', 'shortName': 'Valencia', 'tla': 'VAL', 'crest': 'https://crests.football-data.org/95.png'}, 'playedGames': 28, 'form': None, 'won': 8, 'draw': 8, 'lost': 12, 'points': 32, 'goalsFor': 30, 'goalsAgainst': 42, 'goalDifference': -12}
{'position': 14, 'team': {'id': 559, 'name': 'Sevilla FC', 'shortName': 'Sevilla FC', 'tla': 'SEV', 'crest': 'https://crests.football-data.org/559.png'}, 'playedGames': 27, 'form': None, 'won': 8, 'draw': 7, 'lost': 12, 'points': 31, 'goalsFor': 35, 'goalsAgainst': 42, 'goalDifference': -7}
{'position': 15, 'team': {'id': 87, 'name': 'Rayo Vallecano de Madrid', 'shortName': 'Rayo Vallecano', 'tla': 'RAY', 'crest': 'https://crests.football-data.org/87.png'}, 'playedGames': 27, 'form': None, 'won': 7, 'draw': 10, 'lost': 10, 'points': 31, 'goalsFor': 27, 'goalsAgainst': 33, 'goalDifference': -6}
{'position': 16, 'team': {'id': 263, 'name': 'Deportivo Alavés', 'shortName': 'Alavés', 'tla': 'ALA', 'crest': 'https://crests.football-data.org/263.png'}, 'playedGames': 28, 'form': None, 'won': 7, 'draw': 7, 'lost': 14, 'points': 28, 'goalsFor': 26, 'goalsAgainst': 38, 'goalDifference': -12}
{'position': 17, 'team': {'id': 285, 'name': 'Elche CF', 'shortName': 'Elche', 'tla': 'ELC', 'crest': 'https://crests.football-data.org/285.png'}, 'playedGames': 28, 'form': None, 'won': 5, 'draw': 11, 'lost': 12, 'points': 26, 'goalsFor': 36, 'goalsAgainst': 45, 'goalDifference': -9}
{'position': 18, 'team': {'id': 89, 'name': 'RCD Mallorca', 'shortName': 'Mallorca', 'tla': 'MAL', 'crest': 'https://crests.football-data.org/89.png'}, 'playedGames': 27, 'form': None, 'won': 6, 'draw': 7, 'lost': 14, 'points': 25, 'goalsFor': 31, 'goalsAgainst': 44, 'goalDifference': -13}
{'position': 19, 'team': {'id': 88, 'name': 'Levante UD', 'shortName': 'Levante', 'tla': 'LEV', 'crest': 'https://crests.football-data.org/88.png'}, 'playedGames': 27, 'form': None, 'won': 5, 'draw': 7, 'lost': 15, 'points': 22, 'goalsFor': 29, 'goalsAgainst': 45, 'goalDifference': -16}
{'position': 20, 'team': {'id': 1048, 'name': 'Real Oviedo', 'shortName': 'Real Oviedo', 'tla': 'OVI', 'crest': 'https://crests.football-data.org/1048.png'}, 'playedGames': 28, 'form': None, 'won': 4, 'draw': 9, 'lost': 15, 'points': 21, 'goalsFor': 18, 'goalsAgainst': 44, 'goalDifference': -26}

 Los datos sacados del API te dan los el detalle del global de la campaña no de la jornada
 Por ende se sacara el detalle desde la tabla fact_partido y se calculara el standing jornada a jornada para luego comparar con el standing que da el API y ver si coincide o no. Esto se hara en la fase de Transformacion.

## Informacion de los partidos

In [45]:
df = pd.read_csv(r'C:\Users\brger\OneDrive\Desktop\Project\Football_Prediction\Data\SP1.csv',sep=',')
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,SP1,15/08/2025,18:00,Girona,Vallecano,1,3,A,0,3,...,2.1,1.78,1.97,1.95,2.10,1.80,1.95,1.75,2.11,1.89
1,SP1,15/08/2025,20:30,Villarreal,Oviedo,2,0,H,2,0,...,1.9,1.95,1.93,2.00,1.94,1.96,1.82,1.87,1.96,2.02
2,SP1,16/08/2025,18:30,Mallorca,Barcelona,0,3,A,0,2,...,2.0,1.85,1.88,2.05,2.00,1.93,1.90,1.86,2.04,1.94
3,SP1,16/08/2025,20:30,Alaves,Levante,2,1,H,1,0,...,1.8,2.05,1.86,2.07,1.80,2.07,1.70,2.00,1.81,2.20
4,SP1,16/08/2025,20:30,Valencia,Sociedad,1,1,D,0,0,...,2.1,1.78,2.13,1.81,2.10,1.78,1.96,1.74,2.18,1.84

In [46]:
print(sorted(df['HomeTeam'].unique()))

['Alaves', 'Ath Bilbao', 'Ath Madrid', 'Barcelona', 'Betis', 'Celta', 'Elche', 'Espanol', 'Getafe', 'Girona', 'Levante', 'Mallorca', 'Osasuna', 'Oviedo', 'Real Madrid', 'Sevilla', 'Sociedad', 'Valencia', 'Vallecano', 'Villarreal']

In [47]:
df_equipos = pd.read_sql_query("SELECT id_equipo, nombre, nombre_corto FROM dim_equipo", conn)
print(df_equipos.to_string())

    id_equipo                     nombre    nombre_corto
0          77              Athletic Club        Athletic
1          78    Club Atlético de Madrid          Atleti
2          79                 CA Osasuna         Osasuna
3          80  RCD Espanyol de Barcelona        Espanyol
4          81               FC Barcelona           Barça
5          82                  Getafe CF          Getafe
6          86             Real Madrid CF     Real Madrid
7          87   Rayo Vallecano de Madrid  Rayo Vallecano
8          88                 Levante UD         Levante
9          89               RCD Mallorca        Mallorca
10         90        Real Betis Balompié      Real Betis
11         92    Real Sociedad de Fútbol   Real Sociedad
12         94              Villarreal CF      Villarreal
13         95                Valencia CF        Valencia
14        263           Deportivo Alavés          Alavés
15        285                   Elche CF           Elche
16        298                  Girona FC          Girona
17        558           RC Celta de Vigo           Celta
18        559                 Sevilla FC      Sevilla FC
19       1048                Real Oviedo     Real Oviedo

C:\Users\brger\AppData\Local\Temp\ipykernel_15200\2390548524.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_equipos = pd.read_sql_query("SELECT id_equipo, nombre, nombre_corto FROM dim_equipo", conn)